project:
  type: website
  output-dir: docs

website:
  title: "quarto-test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - others.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
